// Datos para el bloque "Hoy" del inicio: el santo o la fiesta del día y una frase de la Biblia.
// Para corregir o sumar algo, alcanza con editar este archivo.

/**
 * Santos y fiestas de fecha fija, con la clave "mes-día". Son las del calendario general de la
 * Iglesia y algunas propias de la Argentina. Los días que no figuran no muestran santo.
 * Las fiestas que cambian de fecha cada año (Pascua, Pentecostés, Corpus) no están acá: van en el calendario.
 */
export const SANTORAL: Record<string, string> = {
  '01-01': 'Santa María, Madre de Dios',
  '01-02': 'Santos Basilio Magno y Gregorio Nacianceno',
  '01-17': 'San Antonio, abad',
  '01-20': 'San Sebastián',
  '01-21': 'Santa Inés',
  '01-24': 'San Francisco de Sales',
  '01-25': 'La conversión de san Pablo',
  '01-26': 'Santos Timoteo y Tito',
  '01-28': 'Santo Tomás de Aquino',
  '01-31': 'San Juan Bosco',
  '02-02': 'La Presentación del Señor',
  '02-05': 'Santa Águeda',
  '02-06': 'San Pablo Miki y compañeros, mártires',
  '02-08': 'Santa Josefina Bakhita',
  '02-10': 'Santa Escolástica',
  '02-11': 'Nuestra Señora de Lourdes',
  '02-14': 'Santos Cirilo y Metodio',
  '02-22': 'La Cátedra de san Pedro',
  '02-23': 'San Policarpo',
  '03-07': 'Santas Perpetua y Felicidad',
  '03-16': 'San José Gabriel del Rosario Brochero',
  '03-17': 'San Patricio',
  '03-19': 'San José',
  '03-25': 'La Anunciación del Señor',
  '04-07': 'San Juan Bautista de La Salle',
  '04-23': 'San Jorge',
  '04-25': 'San Marcos, evangelista',
  '04-27': 'Santo Toribio de Mogrovejo',
  '04-29': 'Santa Catalina de Siena',
  '05-01': 'San José Obrero',
  '05-02': 'San Atanasio',
  '05-03': 'Santos Felipe y Santiago, apóstoles',
  '05-08': 'Nuestra Señora de Luján',
  '05-13': 'Nuestra Señora de Fátima',
  '05-14': 'San Matías, apóstol',
  '05-22': 'Santa Rita de Casia',
  '05-24': 'María Auxiliadora',
  '05-26': 'San Felipe Neri',
  '05-31': 'La Visitación de la Virgen María',
  '06-01': 'San Justino',
  '06-03': 'San Carlos Lwanga y compañeros, mártires',
  '06-05': 'San Bonifacio',
  '06-11': 'San Bernabé, apóstol',
  '06-13': 'San Antonio de Padua',
  '06-21': 'San Luis Gonzaga',
  '06-24': 'El nacimiento de san Juan Bautista',
  '06-28': 'San Ireneo',
  '06-29': 'Santos Pedro y Pablo, apóstoles',
  '07-03': 'Santo Tomás, apóstol',
  '07-09': 'Nuestra Señora de Itatí',
  '07-11': 'San Benito, abad',
  '07-16': 'Nuestra Señora del Carmen',
  '07-22': 'Santa María Magdalena',
  '07-25': 'Santiago, apóstol',
  '07-26': 'Santos Joaquín y Ana',
  '07-29': 'Santos Marta, María y Lázaro',
  '07-31': 'San Ignacio de Loyola',
  '08-01': 'San Alfonso María de Ligorio',
  '08-04': 'San Juan María Vianney',
  '08-06': 'La Transfiguración del Señor',
  '08-07': 'San Cayetano',
  '08-08': 'Santo Domingo',
  '08-10': 'San Lorenzo',
  '08-11': 'Santa Clara',
  '08-14': 'San Maximiliano Kolbe',
  '08-15': 'La Asunción de la Virgen María',
  '08-20': 'San Bernardo',
  '08-21': 'San Pío X',
  '08-22': 'Santa María Reina',
  '08-24': 'San Bartolomé, apóstol',
  '08-26': 'Beato Ceferino Namuncurá',
  '08-27': 'Santa Mónica',
  '08-28': 'San Agustín',
  '08-29': 'El martirio de san Juan Bautista',
  '08-30': 'Santa Rosa de Lima',
  '09-03': 'San Gregorio Magno',
  '09-05': 'Santa Teresa de Calcuta',
  '09-08': 'La Natividad de la Virgen María',
  '09-09': 'San Pedro Claver',
  '09-13': 'San Juan Crisóstomo',
  '09-14': 'La Exaltación de la Santa Cruz',
  '09-15': 'Nuestra Señora de los Dolores',
  '09-16': 'Santos Cornelio y Cipriano',
  '09-21': 'San Mateo, apóstol y evangelista',
  '09-23': 'San Pío de Pietrelcina',
  '09-24': 'Nuestra Señora de la Merced',
  '09-27': 'San Vicente de Paúl',
  '09-29': 'Santos arcángeles Miguel, Gabriel y Rafael',
  '09-30': 'San Jerónimo',
  '10-01': 'Santa Teresita del Niño Jesús',
  '10-02': 'Santos Ángeles Custodios',
  '10-04': 'San Francisco de Asís',
  '10-05': 'Santa Faustina Kowalska',
  '10-07': 'Nuestra Señora del Rosario',
  '10-11': 'San Juan XXIII',
  '10-12': 'Nuestra Señora del Pilar',
  '10-15': 'Santa Teresa de Jesús',
  '10-17': 'San Ignacio de Antioquía',
  '10-18': 'San Lucas, evangelista',
  '10-22': 'San Juan Pablo II',
  '10-28': 'Santos Simón y Judas, apóstoles',
  '11-01': 'Todos los Santos',
  '11-02': 'Conmemoración de todos los fieles difuntos',
  '11-03': 'San Martín de Porres',
  '11-04': 'San Carlos Borromeo',
  '11-09': 'La dedicación de la Basílica de Letrán',
  '11-10': 'San León Magno',
  '11-11': 'San Martín de Tours',
  '11-15': 'San Alberto Magno',
  '11-17': 'Santa Isabel de Hungría',
  '11-21': 'La Presentación de la Virgen María',
  '11-22': 'Santa Cecilia',
  '11-27': 'Nuestra Señora de la Medalla Milagrosa',
  '11-30': 'San Andrés, apóstol',
  '12-03': 'San Francisco Javier',
  '12-06': 'San Nicolás',
  '12-07': 'San Ambrosio',
  '12-08': 'La Inmaculada Concepción de la Virgen María',
  '12-09': 'San Juan Diego',
  '12-12': 'Nuestra Señora de Guadalupe',
  '12-13': 'Santa Lucía',
  '12-14': 'San Juan de la Cruz',
  '12-25': 'La Natividad del Señor',
  '12-26': 'San Esteban',
  '12-27': 'San Juan, apóstol y evangelista',
  '12-28': 'Los Santos Inocentes',
};

/** Frases de la Biblia que van rotando, una por día. */
export const PALABRAS: Array<{ texto: string; cita: string }> = [
  { texto: 'Vayan por todo el mundo y anuncien la Buena Noticia a toda la creación.', cita: 'Mc 16, 15' },
  { texto: 'Vayan y hagan que todos los pueblos sean mis discípulos.', cita: 'Mt 28, 19' },
  { texto: 'Yo estaré siempre con ustedes hasta el fin del mundo.', cita: 'Mt 28, 20' },
  { texto: 'Ámense los unos a los otros, como yo los he amado.', cita: 'Jn 15, 12' },
  { texto: 'Ustedes son mis amigos si hacen lo que yo les mando.', cita: 'Jn 15, 14' },
  { texto: 'Como el Padre me envió a mí, yo también los envío a ustedes.', cita: 'Jn 20, 21' },
  { texto: 'Ustedes son la luz del mundo.', cita: 'Mt 5, 14' },
  { texto: 'Ustedes son la sal de la tierra.', cita: 'Mt 5, 13' },
  { texto: 'Dejen que los niños se acerquen a mí y no se lo impidan.', cita: 'Mc 10, 14' },
  { texto: 'La cosecha es abundante, pero los trabajadores son pocos.', cita: 'Lc 10, 2' },
  { texto: '¡Aquí estoy: envíame!', cita: 'Is 6, 8' },
  { texto: 'Yo soy el Camino, la Verdad y la Vida.', cita: 'Jn 14, 6' },
  { texto: 'Yo soy la luz del mundo.', cita: 'Jn 8, 12' },
  { texto: 'Yo soy el buen Pastor.', cita: 'Jn 10, 11' },
  { texto: 'Yo soy el pan de Vida.', cita: 'Jn 6, 35' },
  { texto: 'Alégrense siempre en el Señor.', cita: 'Flp 4, 4' },
  { texto: 'Yo lo puedo todo en aquel que me conforta.', cita: 'Flp 4, 13' },
  { texto: 'El Señor es mi pastor, nada me puede faltar.', cita: 'Sal 23, 1' },
  { texto: 'Yo soy la servidora del Señor, que se cumpla en mí lo que has dicho.', cita: 'Lc 1, 38' },
  { texto: 'Hagan todo lo que él les diga.', cita: 'Jn 2, 5' },
  { texto: 'Pidan y se les dará; busquen y encontrarán; llamen y se les abrirá.', cita: 'Mt 7, 7' },
  { texto: 'Cada vez que lo hicieron con el más pequeño de mis hermanos, lo hicieron conmigo.', cita: 'Mt 25, 40' },
  { texto: 'Dios es amor.', cita: '1 Jn 4, 8' },
  { texto: 'Dios amó tanto al mundo, que entregó a su Hijo único.', cita: 'Jn 3, 16' },
  { texto: 'Serán mis testigos hasta los confines de la tierra.', cita: 'Hch 1, 8' },
  { texto: '¡Qué hermosos son los pasos de los que anuncian buenas noticias!', cita: 'Rom 10, 15' },
  { texto: 'Habla, Señor, porque tu servidor escucha.', cita: '1 Sam 3, 10' },
  { texto: 'Hagan por los demás lo que quieren que los hombres hagan por ustedes.', cita: 'Lc 6, 31' },
  { texto: 'Vengan a mí todos los que están afligidos y agobiados, y yo los aliviaré.', cita: 'Mt 11, 28' },
  { texto: 'En esto todos reconocerán que ustedes son mis discípulos: en el amor que se tengan los unos a los otros.', cita: 'Jn 13, 35' },
  { texto: 'Este es el día que hizo el Señor: alegrémonos y regocijémonos en él.', cita: 'Sal 118, 24' },
];

/** El santo del día (o null) y la frase que toca, para una fecha "AAAA-MM-DD". */
export function datosDeHoy(ymd: string): { santo: string | null; palabra: { texto: string; cita: string } } {
  const [anio, mes, dia] = ymd.split('-').map(Number);
  // Día del año: así la frase cambia todos los días y la lista se recorre entera antes de repetirse.
  const diaDelAnio = Math.round((Date.UTC(anio, mes - 1, dia) - Date.UTC(anio, 0, 0)) / 86_400_000);
  return { santo: SANTORAL[ymd.slice(5)] ?? null, palabra: PALABRAS[(diaDelAnio + anio) % PALABRAS.length] };
}
